version: 2
executorType: docker
containerInfo:
  - image: elixir:1.5.2
stages:
  build:
    workDir: /home/ubuntu/lob_elixir
    environment:
      - MIX_ENV: "test"
    steps:
      - type: checkout

      - type: cache-restore
        key: dialyzer-v1

      - type: shell
        command: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix compile --warnings-as-errors

      - type: shell
        command: mix coveralls.html --max-cases 1

      - type: shell
        command: mix dogma

      - type: shell
        command: mix dialyzer --halt-exit-status

      - type: cache-save
        key: dialyzer-v1-{{ checksum "_build/test/dialyxir_erlang-20.0.2_elixir-1.5.1_deps-test.plt.hash" }}
        paths:
          - _build/test/dialyxir_erlang-20.0.2_elixir-1.5.1_deps-test.plt
          - _build/test/dialyxir_erlang-20.0.2_elixir-1.5.1_deps-test.plt.hash

experimental:
  notify:
    branches:
      only:
        - master
