version: 2
executorType: docker
containerInfo:
  - image: elixir:1.5.2
stages:
  build:
    workDir: /home/ubuntu/lob_elixir
    environment:
      - MIX_ENV: "test"
    steps:
      - type: checkout

      - type: cache-restore
        key: build-deps-v2-{{ checksum "mix.lock" }}
        key: build-deps-v2-

      - type: shell
        command: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix compile --warnings-as-errors

      - type: shell
        command: mix coveralls.html --max-cases 1

      - type: shell
        command: mix credo

      - type: shell
        command: mix dialyzer --halt-exit-status

      - type: cache-save
        key: build-deps-v2-{{ checksum "mix.lock" }}
        paths:
          - _build
          - deps

experimental:
  notify:
    branches:
      only:
        - master
